# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poPiguOTAdp_jw_UpTExE5-zy8__SZPY

# Generating synthetic data for Credit Risk Portfolio Analysis
"""

import pandas as pd
import numpy as np

np.random.seed(42)

n_customers = 5000

segments = np.random.choice(
    ['Prime', 'Near-Prime', 'Subprime'],
    size=n_customers,
    p=[0.5, 0.3, 0.2]
)

customers = pd.DataFrame({
    'customer_id': range(1, n_customers + 1),
    'age': np.random.randint(21, 75, n_customers),
    'segment': segments
})

# Credit score distribution based on segment
def generate_credit_score(segment):
    if segment == 'Prime':
        return np.random.normal(750, 40)
    elif segment == 'Near-Prime':
        return np.random.normal(680, 50)
    else:
        return np.random.normal(580, 60)

customers['credit_score'] = customers['segment'].apply(generate_credit_score)

# Clip values to realistic bureau range
customers['credit_score'] = customers['credit_score'].clip(300, 850).astype(int)

customers.head()

customers['credit_score'].describe()

# Employement Status
employment_status = []

for segment in customers['segment']:
    if segment == 'Prime':
        employment_status.append(
            np.random.choice(
                ['Employed', 'Self-Employed', 'Unemployed'],
                p=[0.85, 0.10, 0.05]
            )
        )
    elif segment == 'Near-Prime':
        employment_status.append(
            np.random.choice(
                ['Employed', 'Self-Employed', 'Unemployed'],
                p=[0.75, 0.15, 0.10]
            )
        )
    else:
        employment_status.append(
            np.random.choice(
                ['Employed', 'Self-Employed', 'Unemployed'],
                p=[0.60, 0.15, 0.25]
            )
        )

customers['employment_status'] = employment_status

customers['employment_status'].value_counts(normalize=True)

# Add Income
def generate_income(segment, employment):
    if employment == 'Unemployed':
        return np.random.normal(10000, 3000)

    if segment == 'Prime':
        return np.random.normal(55000, 10000)
    elif segment == 'Near-Prime':
        return np.random.normal(40000, 8000)
    else:
        return np.random.normal(28000, 6000)

customers['income'] = customers.apply(
    lambda row: generate_income(row['segment'], row['employment_status']),
    axis=1
)

customers['income'] = customers['income'].clip(8000, None).astype(int)

customers.groupby('segment')['income'].mean()

# Create Accounts Table
accounts = pd.DataFrame()

accounts['account_id'] = range(1, len(customers) + 1)
accounts['customer_id'] = customers['customer_id']

# Credit limit based on segment
def generate_limit(segment):
    if segment == 'Prime':
        return np.random.normal(9000, 2000)
    elif segment == 'Near-Prime':
        return np.random.normal(6000, 1500)
    else:
        return np.random.normal(3500, 1000)

accounts['credit_limit'] = customers['segment'].apply(generate_limit)
accounts['credit_limit'] = accounts['credit_limit'].clip(1000, 15000).astype(int)

# Generate balance correlated with risk
def generate_balance(limit, segment):
    if segment == 'Prime':
        utilisation = np.random.normal(0.45, 0.15)
    elif segment == 'Near-Prime':
        utilisation = np.random.normal(0.65, 0.20)
    else:
        utilisation = np.random.normal(0.85, 0.25)

    utilisation = np.clip(utilisation, 0.05, 1.2)
    return limit * utilisation

accounts['balance'] = accounts.apply(
    lambda row: generate_balance(row['credit_limit'], customers.loc[row.name, 'segment']),
    axis=1
)

accounts['balance'] = accounts['balance'].astype(int)

accounts['utilisation_rate'] = accounts['balance'] / accounts['credit_limit']

accounts.head()

accounts.groupby(customers['segment'])['utilisation_rate'].mean()

# Create Delinquency Behaviour
performance = pd.DataFrame()

performance['account_id'] = accounts['account_id']

def generate_dpd(segment, utilisation):

    base_prob = 0.02

    if segment == 'Prime':
        base_prob = 0.03
    elif segment == 'Near-Prime':
        base_prob = 0.08
    else:
        base_prob = 0.18

    # Increase risk if high utilisation
    if utilisation > 0.85:
        base_prob += 0.10
    elif utilisation > 0.70:
        base_prob += 0.05

    random_value = np.random.rand()

    if random_value < base_prob:
        return np.random.choice([30, 60, 90], p=[0.5, 0.3, 0.2])
    else:
        return 0

performance['days_past_due'] = performance.apply(
    lambda row: generate_dpd(
        customers.loc[row.name, 'segment'],
        accounts.loc[row.name, 'utilisation_rate']
    ),
    axis=1
)

performance.head()

# Check Delinquency Rate
performance['days_past_due'].value_counts(normalize=True)

pd.crosstab(customers['segment'], performance['days_past_due'], normalize='index')

# Set Default Flag
performance['default_flag'] = np.where(
    performance['days_past_due'] >= 90,
    1,
    0
)

pd.crosstab(
    customers['segment'],
    performance['default_flag'],
    normalize='index'
)

# Create Master Dataset
portfolio = customers.merge(accounts, on='customer_id')
portfolio = portfolio.merge(performance, on='account_id')

portfolio.head()

portfolio.shape

# Compute Core Risk KPIs
# Overall portfolio metrics
overall_default_rate = portfolio['default_flag'].mean()
overall_delinquency_rate = (portfolio['days_past_due'] > 0).mean()
avg_utilisation = portfolio['utilisation_rate'].mean()

overall_default_rate, overall_delinquency_rate, avg_utilisation

# Credit Risk Monitoring Metrics
# Segment-level KPIs
segment_kpis = portfolio.groupby('segment').agg(
    total_accounts=('account_id', 'count'),
    avg_utilisation=('utilisation_rate', 'mean'),
    delinquency_rate=('days_past_due', lambda x: (x > 0).mean()),
    default_rate=('default_flag', 'mean')
).reset_index()

segment_kpis

def assign_risk_level(row):
    score = 0

    if row['utilisation_rate'] > 0.85:
        score += 2
    elif row['utilisation_rate'] > 0.70:
        score += 1

    if row['days_past_due'] > 0:
        score += 2

    if row['credit_score'] < 600:
        score += 1

    if score >= 3:
        return 'High'
    elif score == 2:
        return 'Medium'
    else:
        return 'Low'

portfolio['risk_level'] = portfolio.apply(assign_risk_level, axis=1)

pd.crosstab(portfolio['segment'], portfolio['risk_level'], normalize='index')

print('Customers Table: ', customers.shape)
print('Accounts Table: ', accounts.shape)
print('Performance Table: ', performance.shape)
print('Portfolio Table: ', portfolio.shape)

# Export CSV files
customers.to_csv("customers.csv", index=False)
accounts.to_csv("accounts.csv", index=False)
performance.to_csv("performance.csv", index=False)
portfolio.to_csv("portfolio_master.csv", index=False)